sudo: required
services:
  - docker

before_install:
  - docker build -t mahdiahmed/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mahdiahmed/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: elasticbeanstalk-ap-southeast-1-151612831342
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
